### PR TITLE
Turn setFadeDurations public

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by capybaracreations** [comment]
@amlcurran please merge. I believe that having this method as private is a major issue with this library.

**Comment by tomredman** [comment]
Until this is `public`, you can use reflection to change these fields :)

```java
try {
    Field field = ShowcaseView.class.getDeclaredField("fadeInMillis");
    field.setAccessible(true);
    field.setLong(showcaseView, 1000);
}
catch (NoSuchFieldException e) {
    // The Showcase API changed. Oh well.
}
catch (IllegalAccessException e) {
    // Whoops, no access.
}
```

**Comment by bryant1410** [comment]
Or use the forked version :smile:

**Comment by amlcurran** [comment]
Going to merge it, will try to do a release later this week

**Pull request merged**
