### PR TITLE
makes it workable with api9 and 10

### PR DESCRIPTION
**Pull request by boeserwolf91**
The minimun version of the library is set to android sdk 9 but unfortunately it doesn't work with an android version before sdk 11. This PR fixes this problem. It simply disables the animations for android 9 and 10. So if the showcase position changes it'll just jump to the new position. For me this behavior is okay for this old android versions.

### CODE REVIEW

**Comment by amlcurran** [comment]
Hi! Thanks for the PR, and sorry it isn't working. 

I like what you've done, although would you mind doing it a slightly different way? If you see here https://github.com/amlcurran/ShowcaseView/blob/master/library/src/main/java/com/github/amlcurran/showcaseview/ShowcaseView.java#L96 I create an animator factory. Essentially, I was going to use polymorphism and make an animator factory that doesn't do animations. Would you mind doing it this way? 

If you're not sure of what I mean then let me know; I'll be happy to accept the pull request and do it myself if so :) 

Thanks!

**Comment by boeserwolf91** [comment]
Thanks for your feedback. Yes, I know what you mean. I'll change my PR Wednesday and ping you if it's ready. Unfortunately I won't have time earlier.

**Comment by boeserwolf91** [comment]
@amlcurran I updated the PR. I hope I did it like you want it. I'm not sure about the name of the AnimationFactory. I called it "Jumping" because it doesn't animate, it just jumps from one point to another. Let me know if you've a better name.

**Comment by amlcurran** [comment]
This is exactly what I was looking for :) going to make a few style changes, but more than happy to accept this. Thanks!!

**Pull request merged**
