### PR TITLE
fixes some memory leaks

### PR DESCRIPTION
**Pull request by csoltenborn**
hide() needs to be called to free resources - usage pattern:

	final ShowcaseView view = builder.build();
	view.overrideButtonClick(new OnClickListener() {

		@Override
		public void onClick(View v) {
			view.hide();
		}
	});
	if (view.hasShot()) {
		view.hide();
	}

### CODE REVIEW

**Comment by mattiasbe** [comment]
To be clear, hide(), is usually called for you though

**Comment by mattiasbe** [comment]
This was needed but not enough for me to get rid of the out of memory errors. I also had to add this to all didHide events: 
```
.setShowcaseEventListener(new OnShowcaseEventListener() {

                            @Override
                            public void onShowcaseViewShow(final ShowcaseView scv) {
                            }

                            @Override
                            public void onShowcaseViewHide(final ShowcaseView scv) {
                            }

                            @Override
                            public void onShowcaseViewDidHide(final ShowcaseView scv) {
                                commonHide(scv);
                                show2(activity);
                            }

                        })

static void commonHide(ShowcaseView scv) {
        scv.setOnClickListener(null);
        scv.setOnShowcaseEventListener(null);
        scv.setOnTouchListener(null);
    }
```

**Comment by MarcSalvat** [comment]
Just checked out and it fixed the OutOfMemory problem for me.

thanks!

**Comment by mattiasbe** [comment]
@amlcurran Any updates possible with this, a snapshot perhaps at least with this pull request? Been running this for a few days with a few users and it looks solid.

**Comment by hatpick** [comment]
+1

**Comment by acorrow** [comment]
Is there any chance this is going to make it into a published version?

**Comment by ramannanda9** [comment]
Aha! It is fixed took some effort. It is a guaranteed fix few things need to be changed in hide method. 

First the fatal flaw that you are committing is doing  View.Gone in hide method. Okay, so that does hide the view but does not remove it from the ViewGroup. You need to explicitly do that. This was a major issue. 

Also While doing heap analysis, I found out that certain listeners are attached but never removed. This is a minor issue, but the changes are mentioned below. 

The  method hideImmediate becomes. 
public void hideImmediate() {
        isShowing = false;
        setVisibility(GONE);
        removeView(ShowcaseView.this);
    }

The method hide becomes

 @Override
    public void hide() {
        clearBitmap();
        // If the type is set to one-shot, store that it has shot
        shotStateStore.storeShot();
        mEventListener.onShowcaseViewHide(this);
        fadeOutShowcase();
        getViewTreeObserver().removeOnPreDrawListener(draw);
        if(Build.VERSION.SDK_INT>15){
            getViewTreeObserver().removeOnGlobalLayoutListener(globalLayout);
        }
        else {
            getViewTreeObserver().removeGlobalOnLayoutListener(globalLayout);
        }
        removeView(ShowcaseView.this);
    }

I have also created a gist for this class. 

https://gist.github.com/ramannanda9/7bf837f535b0ba2b96f2#file-showcaseview-java 

Feel free to merge the changes.

**Comment by amlcurran** [comment]
Closing this, I believe it is fixed as of `5.4.0`

**Pull request closed without merging**
